apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tomcat-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-tomcat
  template:
    metadata:
      labels:
        app: nginx-tomcat
    spec:
      containers:
        - name: nginx-container
          image: <your-ecr-url>/nginx:latest
          ports:
            - containerPort: 80
        - name: tomcat-container
          image: <your-ecr-url>/tomcat:latest
          ports:
            - containerPort: 8080
